# Generated by Django 3.2.3 on 2021-06-15 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=99)),
            ],
        ),
        migrations.RenameField(
            model_name='componente',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='componente',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=99)),
                ('Precio', models.IntegerField(default=0)),
                ('Stock', models.IntegerField(default=0)),
                ('Imagen', models.FileField(blank=True, null=True, upload_to='#')),
                ('Componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.componente')),
                ('Fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fabricante')),
            ],
        ),
    ]
