# Generated by Django 3.2.3 on 2021-06-15 22:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210614_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='magen',
            field=models.ImageField(blank=True, max_length=9999, null=True, upload_to=core.models.Producto.ruta_imagen),
        ),
    ]
